### PR TITLE
Add another marketing tool to the list

### PR DESCRIPTION
**Pull request by bakollc-wa**
Hi Marcel

Adding another marketing automation software to the list, do you think this could be added in?

Thank you!

### CODE REVIEW

**Comment by bakollc-wa** [comment]
@marcelkooi Would you be okay adding this tool? Or do you need some additional information? Thanks a lot for your help!

**Comment by marcelkooi** [comment]
@bakollc-wa Merged, thanks! The URL doesn't seem to work for me though. I get a connection timeout from cloudflare

**Comment by bakollc-wa** [comment]
Thank you Marcel! It should be working now. 

Appreciate your help!

**Comment by bakollc-wa** [comment]
Hmm strange seems to be loading for me. Weird, I'll double check it as well.

**Pull request merged**
